const BankActionTypes = {
  WITHDRAW_BELLS: 'WITHDRAW_BELLS',
  DEPOSIT_BELLS: 'DEPOSIT_BELLS',
  WITHDRAWAL_REQUEST: 'WITHDRAWAL_REQUEST',
  WITHDRAWAL_SUCCESS: 'WITHDRAWAL_SUCCESS',
  WITHDRAWAL_FAIL: 'WITHDRAWAL_FAIL',
  DEPOSIT_REQUEST: 'DEPOSIT_REQUEST',
  DEPOSIT_SUCCESS: 'DEPOSIT_SUCCESS',
  DEPOSIT_FAIL: 'DEPOSIT_FAIL'
}
export default BankActionTypes;